### ISSUE TITLE
mahi v1 crash on bad role mgmt log entry

### ISSUE THREAD

**Issue by arekinath** [TritonDataCenter/mahi#19]
UFDS can write log entries out of order, resulting in a log that can't be replayed by mahi. It's fine for mahi to stop replicating in this situation, but it should not crash.

Currently if you quickly add a user to a role and remove them, and the log entries get re-ordered, then mahi v1 will crash in `auth_cache.js` around line 738. It should either truck on (because mahi v1 is loosey goosey about that generally) or stop replicating, not crash.

**Comment by danmcd** [comment]
https://github.com/TritonDataCenter/mahi/commit/bcc382b49094144f9fd93f5dff41e57cd0630afb

**Comment by bahamat** [comment]
Originally #20, ultimately merged in #21.
